telegram:
  # Get API ID and API Hash https://core.telegram.org/api/obtaining_api_id
  api_id: 
  api_hash: 

discord:
  # Get the token and app ID from your bot's info in https://discord.com/developers/applications/
  token: 
  app_id: 

bridges:
  - name: first bridge # Bridges names doesn't matter but they must be different from each other.
    telegram_chat_id: -123456 # Replace this with your telegram chat id. Inlcude the '-'
    discord_chat_id: 123456789 # Replace this with your discord chat id.

  # Repeat for any number of bridges you want.
  - name: second bridge
    telegram_chat_id: -123456
    discord_chat_id: 123456789